source "https://supermarket.chef.io"
cookbook 'apt'
cookbook 'gengine', github: "manabuishii/gengine-chef-cookbook"
cookbook 'docker-install', github: "manabuishii/docker-install-cookbook"
cookbook 'basicsetup', github: "BioDevOps/basicsetup", branch: "1.3.0-dev"